/**
 * This module handles constants logic.
 */
"use strict";

const CAPTURE_MODE_LITE = "lite";
const CAPTURE_MODE_FULL = "full";
const DEFAULT_CAPTURE_MODE = CAPTURE_MODE_LITE;
const DEFAULT_SUBFOLDER = "ai-knowledge";

const ENV_KEY_VAULT_PATH = "MEMORY_MASON_VAULT_PATH";
const ENV_KEY_SUBFOLDER = "MEMORY_MASON_SUBFOLDER";
const ENV_KEY_SYNC = "MEMORY_MASON_SYNC";
const ENV_KEY_CAPTURE_MODE = "MEMORY_MASON_CAPTURE_MODE";
const ENV_KEY_MINIMIZE = "MEMORY_MASON_MINIMIZE";
const ENV_KEY_INVOKED_BY = "MEMORY_MASON_INVOKED_BY";

const CONFIG_KEY_VAULT_PATH = "vaultPath";
const CONFIG_KEY_SUBFOLDER = "subfolder";
const CONFIG_KEY_SYNC = "sync";
const CONFIG_KEY_CAPTURE_MODE = "captureMode";
const CONFIG_KEY_MINIMIZE = "minimize";

const DEFAULT_MINIMIZE = false;

const PROJECT_CONFIG_FILE_NAME = "memory-mason.json";
const DOTENV_FILE_NAME = ".env";
const GLOBAL_MM_DIR_NAME = ".memory-mason";
const GLOBAL_CONFIG_FILE_NAME = "config.json";

module.exports = {
  CAPTURE_MODE_LITE,
  CAPTURE_MODE_FULL,
  DEFAULT_CAPTURE_MODE,
  DEFAULT_SUBFOLDER,
  DEFAULT_MINIMIZE,
  ENV_KEY_VAULT_PATH,
  ENV_KEY_SUBFOLDER,
  ENV_KEY_SYNC,
  ENV_KEY_CAPTURE_MODE,
  ENV_KEY_MINIMIZE,
  ENV_KEY_INVOKED_BY,
  CONFIG_KEY_VAULT_PATH,
  CONFIG_KEY_SUBFOLDER,
  CONFIG_KEY_SYNC,
  CONFIG_KEY_CAPTURE_MODE,
  CONFIG_KEY_MINIMIZE,
  PROJECT_CONFIG_FILE_NAME,
  DOTENV_FILE_NAME,
  GLOBAL_MM_DIR_NAME,
  GLOBAL_CONFIG_FILE_NAME,
};
