"use strict";

const ENV_KEY_VAULT_PATH = "MEMORY_MASON_VAULT_PATH";
const ENV_KEY_SUBFOLDER = "MEMORY_MASON_SUBFOLDER";
const ENV_KEY_SYNC = "MEMORY_MASON_SYNC";
const ENV_KEY_CAPTURE_MODE = "MEMORY_MASON_CAPTURE_MODE";
const ENV_KEY_INVOKED_BY = "MEMORY_MASON_INVOKED_BY";

const CONFIG_KEY_VAULT_PATH = "vaultPath";
const CONFIG_KEY_SUBFOLDER = "subfolder";
const CONFIG_KEY_SYNC = "sync";
const CONFIG_KEY_CAPTURE_MODE = "captureMode";

const PROJECT_CONFIG_FILE_NAME = "memory-mason.json";
const DOTENV_FILE_NAME = ".env";
const GLOBAL_MM_DIR_NAME = ".memory-mason";
const GLOBAL_CONFIG_FILE_NAME = "config.json";

module.exports = {
  ENV_KEY_VAULT_PATH,
  ENV_KEY_SUBFOLDER,
  ENV_KEY_SYNC,
  ENV_KEY_CAPTURE_MODE,
  ENV_KEY_INVOKED_BY,
  CONFIG_KEY_VAULT_PATH,
  CONFIG_KEY_SUBFOLDER,
  CONFIG_KEY_SYNC,
  CONFIG_KEY_CAPTURE_MODE,
  PROJECT_CONFIG_FILE_NAME,
  DOTENV_FILE_NAME,
  GLOBAL_MM_DIR_NAME,
  GLOBAL_CONFIG_FILE_NAME,
};
