"use strict";

const CAPTURE_MODE_LITE = "lite";
const CAPTURE_MODE_FULL = "full";
const DEFAULT_CAPTURE_MODE = CAPTURE_MODE_LITE;
const DEFAULT_SUBFOLDER = "ai-knowledge";
const HOOK_EVENT_STOP = "stop";
const DUPLICATE_CAPTURE_WINDOW_MS = 60000;

const STDIN_BUFFER_BYTES = 65536;

const DEFAULT_DAILY_CHUNK_CAP_BYTES = 512000;
const MAX_DAILY_CHUNK_COUNT = 999;
const CHUNK_ID_WIDTH = 3;

const CAPTURE_HASH_ALGORITHM = "sha256";
const CAPTURE_HASH_PREFIX_LENGTH = 16;

const OBSIDIAN_CLI_TIMEOUT_MS = 8000;

const SESSION_START_RECENT_LOG_LINES = 30;
const HOT_CACHE_CONTEXT_MAX_CHARS = 5000;
const INDEX_CONTEXT_MAX_CHARS = 10000;

const PRE_COMPACT_MIN_TURNS = 5;

const USER_INPUT_TOOLS = new Set(["AskUserQuestion"]);

const NOISY_TOOLS = new Set(["Read", "Glob", "LS", "List", "ls", "read", "glob"]);

module.exports = {
  CAPTURE_MODE_LITE,
  CAPTURE_MODE_FULL,
  DEFAULT_CAPTURE_MODE,
  DEFAULT_SUBFOLDER,
  HOOK_EVENT_STOP,
  DUPLICATE_CAPTURE_WINDOW_MS,
  STDIN_BUFFER_BYTES,
  DEFAULT_DAILY_CHUNK_CAP_BYTES,
  MAX_DAILY_CHUNK_COUNT,
  CHUNK_ID_WIDTH,
  CAPTURE_HASH_ALGORITHM,
  CAPTURE_HASH_PREFIX_LENGTH,
  OBSIDIAN_CLI_TIMEOUT_MS,
  SESSION_START_RECENT_LOG_LINES,
  HOT_CACHE_CONTEXT_MAX_CHARS,
  INDEX_CONTEXT_MAX_CHARS,
  PRE_COMPACT_MIN_TURNS,
  USER_INPUT_TOOLS,
  NOISY_TOOLS,
};
