"use strict";

const HOOK_ENTRY_SESSION_START = "SessionStart";
const HOOK_ENTRY_USER_PROMPT = "UserPrompt";
const HOOK_ENTRY_USER_PROMPT_EXPANSION = "UserPromptExpansion";
const HOOK_ENTRY_USER_PROMPT_SUBMIT = "UserPromptSubmit";
const HOOK_ENTRY_POST_TOOL_USE = "PostToolUse";
const HOOK_EVENT_POST_TOOL_USE_KEBAB = "post-tool-use";
const HOOK_EVENT_USER_PROMPT_SUBMIT_KEBAB = "user-prompt-submit";
const HOOK_EVENT_PRE_COMPACT_KEBAB = "pre-compact";

module.exports = {
  HOOK_ENTRY_SESSION_START,
  HOOK_ENTRY_USER_PROMPT,
  HOOK_ENTRY_USER_PROMPT_EXPANSION,
  HOOK_ENTRY_USER_PROMPT_SUBMIT,
  HOOK_ENTRY_POST_TOOL_USE,
  HOOK_EVENT_POST_TOOL_USE_KEBAB,
  HOOK_EVENT_USER_PROMPT_SUBMIT_KEBAB,
  HOOK_EVENT_PRE_COMPACT_KEBAB,
};
