/**
 * This module handles constants logic.
 */
"use strict";

const DUPLICATE_CAPTURE_WINDOW_MS = 60000;
const CAPTURE_HASH_ALGORITHM = "sha256";
const CAPTURE_HASH_PREFIX_LENGTH = 16;
const COACHING_NAG_THRESHOLD = 5;
const COACHING_NAG_SESSION_MEMORY = 3;
const COACHING_HASH_COUNTS_MAX = 500;
const COACHING_LRU_LOW_USE_FLOOR = 3;

module.exports = {
  DUPLICATE_CAPTURE_WINDOW_MS,
  CAPTURE_HASH_ALGORITHM,
  CAPTURE_HASH_PREFIX_LENGTH,
  COACHING_NAG_THRESHOLD,
  COACHING_NAG_SESSION_MEMORY,
  COACHING_HASH_COUNTS_MAX,
  COACHING_LRU_LOW_USE_FLOOR,
};
