/**
 * This module handles constants logic.
 */
"use strict";

const DUPLICATE_CAPTURE_WINDOW_MS = 60000;
const CAPTURE_HASH_ALGORITHM = "sha256";
const CAPTURE_HASH_PREFIX_LENGTH = 16;
const COACHING_NAG_THRESHOLD = 5;
const COACHING_NAG_SESSION_MEMORY = 3;
const COACHING_HASH_COUNTS_MAX = 500;
const COACHING_LRU_LOW_USE_FLOOR = 3;
const COACHING_DECAY_MS = 2592000000;
const COACHING_DECAY_NAGGED_WINDOW_MS = 7776000000;
const COACHING_KIND_PROMPT_REPEAT = "prompt-repeat";
const COACHING_KIND_ERROR_REPEAT = "error-repeat";
const EXCHANGE_STALE_OPEN_MS = 86400000;

module.exports = {
  DUPLICATE_CAPTURE_WINDOW_MS,
  CAPTURE_HASH_ALGORITHM,
  CAPTURE_HASH_PREFIX_LENGTH,
  COACHING_NAG_THRESHOLD,
  COACHING_NAG_SESSION_MEMORY,
  COACHING_HASH_COUNTS_MAX,
  COACHING_LRU_LOW_USE_FLOOR,
  COACHING_DECAY_MS,
  COACHING_DECAY_NAGGED_WINDOW_MS,
  COACHING_KIND_PROMPT_REPEAT,
  COACHING_KIND_ERROR_REPEAT,
  EXCHANGE_STALE_OPEN_MS,
};
