/**
 * This module handles constants logic.
 */
"use strict";

const DEFAULT_DAILY_CHUNK_CAP_BYTES = 512000;
const DAILY_CHUNK_HARD_CAP_BYTES = 2097152;
const MAX_DAILY_CHUNK_COUNT = 999;
const CHUNK_ID_WIDTH = 3;
const SESSION_CHUNK_TIME_WIDTH = 6;
const SESSION_ID_SHORT_LENGTH = 8;
const NO_SESSION_SID = "nosession";
const DAILY_META_SCHEMA_VERSION = 2;
const CONTINUED_CALLOUT_LINE = "> [!continued]";
const OBSIDIAN_CLI_TIMEOUT_MS = 8000;
const SESSION_START_RECENT_LOG_LINES = 30;
const HOT_CACHE_CONTEXT_MAX_CHARS = 5000;
const INDEX_CONTEXT_MAX_CHARS = 10000;

module.exports = {
  DEFAULT_DAILY_CHUNK_CAP_BYTES,
  DAILY_CHUNK_HARD_CAP_BYTES,
  MAX_DAILY_CHUNK_COUNT,
  CHUNK_ID_WIDTH,
  SESSION_CHUNK_TIME_WIDTH,
  SESSION_ID_SHORT_LENGTH,
  NO_SESSION_SID,
  DAILY_META_SCHEMA_VERSION,
  CONTINUED_CALLOUT_LINE,
  OBSIDIAN_CLI_TIMEOUT_MS,
  SESSION_START_RECENT_LOG_LINES,
  HOT_CACHE_CONTEXT_MAX_CHARS,
  INDEX_CONTEXT_MAX_CHARS,
};
